### ISSUE TITLE
wp: unbound variable while installing plugins

### ISSUE THREAD

**Issue by Arsalanliaqat** [ellakcy/wordpressWithPlugins#2]
$wp --allow-root --path=/var/www/html plugin install twitter --activate

**Comment by Arsalanliaqat** [comment]
wordpress_1   | Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress installation exists under.
wordpress_1   |
wordpress_1   | If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.
wordpress_1   |
wordpress_1   | If you'd like to continue as root, please run this again, adding this flag:  --allow-root
wordpress_1   |
wordpress_1   | If you'd like to run it as the user that this site is under, you can run the following to become the respective user:
wordpress_1   |
wordpress_1   |     sudo -u USER -i -- wp <command>

`wp --allow-root --path=/var/www/html plugin install twitter --activate`

**Comment by pc-magas** [comment]
Fixed the Issue pull newer images. Also you can use this repo to build your own.
